# 基础镜像
FROM redis
# author
MAINTAINER damao

# 挂载目录
VOLUME /home/liveclub/redis
# 创建目录
RUN mkdir -p /home/liveclub/redis
# 指定路径
WORKDIR /home/liveclub/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/liveclub/redis/redis.conf
