# 基础镜像
FROM nginx
# author
MAINTAINER damao

# 挂载目录
VOLUME /home/liveclub/projects/liveclub-ui
# 创建目录
RUN mkdir -p /home/liveclub/projects/liveclub-ui
# 指定路径
WORKDIR /home/liveclub/projects/liveclub-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/liveclub/projects/liveclub-ui
